# Generated by Django 5.2.7 on 2026-05-14 06:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_datetime', models.DateTimeField()),
                ('event_title', models.CharField(max_length=200)),
                ('organizer', models.ForeignKey(db_column='organizer_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticket_category.organizer')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('quota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='ticket_category.event')),
            ],
            options={
                'db_table': 'TICKET_CATEGORY',
                'ordering': ['event__event_title', '-price'],
            },
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='ticket_category.useraccount'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'venue',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='check_capacity_positive')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ticket_category.venue'),
        ),
    ]
