# Generated by Django 6.0.4 on 2026-05-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['event_name', 'price']},
        ),
    ]
