# Generated by Django 6.0.4 on 2026-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_category', '0002_alter_ticketcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['event_name', '-price']},
        ),
    ]
