# Generated by Django 5.2.7 on 2026-05-14 09:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ARTIST',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_datetime', models.DateTimeField()),
                ('event_title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'EVENT',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizer_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ORGANIZER',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ROLE',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=10)),
                ('row_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SEAT',
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.artist')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
            ],
            options={
                'db_table': 'EVENT_ARTIST',
                'unique_together': {('event', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', through='dashboard.EventArtist', to='dashboard.artist'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(db_column='organizer_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.organizer'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('NOMINAL', 'Nominal'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('usage_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'PROMOTION',
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_type__in', ['NOMINAL', 'PERCENTAGE'])), name='discount_type_check'), models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='discount_value_check'), models.CheckConstraint(condition=models.Q(('usage_limit__gt', 0)), name='usage_limit_check')],
            },
        ),
        migrations.CreateModel(
            name='OrderPromotion',
            fields=[
                ('order_promotion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotion')),
            ],
            options={
                'db_table': 'ORDER_PROMOTION',
            },
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.role')),
            ],
            options={
                'db_table': 'ACCOUNT_ROLE',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('quota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tevent', models.ForeignKey(db_column='tevent_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='dashboard.event')),
            ],
            options={
                'db_table': 'TICKET_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer')),
                ('promotions', models.ManyToManyField(related_name='orders', through='dashboard.OrderPromotion', to='dashboard.promotion')),
            ],
            options={
                'db_table': 'TICKET_ORDER',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('seats', models.ManyToManyField(db_table='HAS_RELATIONSHIP', related_name='tickets', to='dashboard.seat')),
                ('tcategory', models.ForeignKey(db_column='tcategory_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dashboard.ticketcategory')),
                ('torder', models.ForeignKey(db_column='torder_id', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dashboard.ticketorder')),
            ],
            options={
                'db_table': 'TICKET',
            },
        ),
        migrations.AddField(
            model_name='orderpromotion',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticketorder'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roles', models.ManyToManyField(related_name='users', through='dashboard.AccountRole', to='dashboard.role')),
            ],
            options={
                'db_table': 'USER_ACCOUNT',
            },
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='dashboard.useraccount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='dashboard.useraccount'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.useraccount'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VENUE',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='capacity_check')],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='dashboard.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.venue'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(('quota__gt', 0)), name='quota_check'),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_check'),
        ),
        migrations.AddConstraint(
            model_name='ticketorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='total_amount_check'),
        ),
        migrations.AlterUniqueTogether(
            name='orderpromotion',
            unique_together={('promotion', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='accountrole',
            unique_together={('role', 'user')},
        ),
    ]
