# Generated by Django 5.2.7 on 2026-05-07 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ARTIST',
                'ordering': ['name'],
            },
        ),
    ]
